//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dokkasz.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Egyseg
    {
        public int Id { get; set; }
        public string Kod { get; set; }
        public string Megnevezes { get; set; }
        public bool Afa { get; set; }
        public byte[] RowVersion { get; set; }
    }
}
