//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dokkasz.Model
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Teszt
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public Nullable<int> Fizetes { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
